Load libraries/packages

In [1]:
import pandas as pd
import numpy as np
import sqlite3

In [2]:
df = pd.read_csv("../DataCo/DataCoSupplyChainDataset.csv", encoding='latin1')
print(f"Data loaded successfull! Shape: {df.shape}")

Data loaded successfull! Shape: (180519, 53)

This data has 53 columns with string, integer and float types.The columns are information of shipping dates, customer information, delivery status, risk, ...

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 128.3 MB

There is no null value but there are NaN values

In [4]:
print(f"First few lines of the data:\n {pd.DataFrame(df.head())}")

First few lines of the data:
        Type  Days for shipping (real)  Days for shipment (scheduled)  \
0     DEBIT                         3                              4
1  TRANSFER                         5                              4
2      CASH                         4                              4
3     DEBIT                         3                              4
4   PAYMENT                         2                              4

   Benefit per order  Sales per customer   Delivery Status  \
0          91.250000          314.640015  Advance shipping
1        -249.089996          311.359985     Late delivery
2        -247.779999          309.720001  Shipping on time
3          22.860001          304.809998  Advance shipping
4         134.210007          298.250000  Advance shipping

   Late_delivery_risk  Category Id   Category Name Customer City  ...  \
0                   0           73  Sporting Goods        Caguas  ...
1                   1           73  Sporting Goods        Caguas  ...
2                   0           73  Sporting Goods      San Jose  ...
3                   0           73  Sporting Goods   Los Angeles  ...
4                   0           73  Sporting Goods        Caguas  ...

  Order Zipcode Product Card Id Product Category Id  Product Description  \
0           NaN            1360                  73                  NaN
1           NaN            1360                  73                  NaN
2           NaN            1360                  73                  NaN
3           NaN            1360                  73                  NaN
4           NaN            1360                  73                  NaN

                                  Product Image  Product Name Product Price  \
0  http://images.acmesports.sports/Smart+watch   Smart watch         327.75
1  http://images.acmesports.sports/Smart+watch   Smart watch         327.75
2  http://images.acmesports.sports/Smart+watch   Smart watch         327.75
3  http://images.acmesports.sports/Smart+watch   Smart watch         327.75
4  http://images.acmesports.sports/Smart+watch   Smart watch         327.75

  Product Status shipping date (DateOrders)   Shipping Mode
0              0             2/3/2018 22:56  Standard Class
1              0            1/18/2018 12:27  Standard Class
2              0            1/17/2018 12:06  Standard Class
3              0            1/16/2018 11:45  Standard Class
4              0            1/15/2018 11:24  Standard Class

[5 rows x 53 columns]

Clean column names so they are easy to use in SQL

In [5]:
df.columns = df.columns.str.strip().str.lower().str.replace(r"[^a-z0-9]+", "_", regex=True).str.strip("_")

In [6]:
df.order_date_dateorders = pd.to_datetime(df.order_date_dateorders, format ="%m/%d/%Y %H:%M")
df.shipping_date_dateorders = pd.to_datetime(df.shipping_date_dateorders, format ="%m/%d/%Y %H:%M")

In [7]:
#dropping useless comlumns (customer's information and product_description-null values and product_image)
df = df.drop(columns = ["customer_email", "customer_password", "customer_fname", "customer_lname", "customer_street", "product_description", "product_image"])

Open a connection to local database (if the supply_chain.db is not there, running this line will create a new one)

In [8]:
conn = sqlite3.connect("../data/supply_chain.db")

Write the data from DataCoSupplyChainDataset.csv to the database supply_chain.db

In [9]:
df.to_sql("supply_chain", conn, if_exists='replace', index = False)

180519

In [10]:
pd.read_sql("PRAGMA table_info(supply_chain);", conn)

    cid                         name       type  notnull dflt_value  pk
0     0                         type       TEXT        0       None   0
1     1       days_for_shipping_real    INTEGER        0       None   0
2     2  days_for_shipment_scheduled    INTEGER        0       None   0
3     3            benefit_per_order       REAL        0       None   0
4     4           sales_per_customer       REAL        0       None   0
5     5              delivery_status       TEXT        0       None   0
6     6           late_delivery_risk    INTEGER        0       None   0
7     7                  category_id    INTEGER        0       None   0
8     8                category_name       TEXT        0       None   0
9     9                customer_city       TEXT        0       None   0
10   10             customer_country       TEXT        0       None   0
11   11                  customer_id    INTEGER        0       None   0
12   12             customer_segment       TEXT        0       None   0
13   13               customer_state       TEXT        0       None   0
14   14             customer_zipcode       REAL        0       None   0
15   15                department_id    INTEGER        0       None   0
16   16              department_name       TEXT        0       None   0
17   17                     latitude       REAL        0       None   0
18   18                    longitude       REAL        0       None   0
19   19                       market       TEXT        0       None   0
20   20                   order_city       TEXT        0       None   0
21   21                order_country       TEXT        0       None   0
22   22            order_customer_id    INTEGER        0       None   0
23   23        order_date_dateorders  TIMESTAMP        0       None   0
24   24                     order_id    INTEGER        0       None   0
25   25       order_item_cardprod_id    INTEGER        0       None   0
26   26          order_item_discount       REAL        0       None   0
27   27     order_item_discount_rate       REAL        0       None   0
28   28                order_item_id    INTEGER        0       None   0
29   29     order_item_product_price       REAL        0       None   0
30   30      order_item_profit_ratio       REAL        0       None   0
31   31          order_item_quantity    INTEGER        0       None   0
32   32                        sales       REAL        0       None   0
33   33             order_item_total       REAL        0       None   0
34   34       order_profit_per_order       REAL        0       None   0
35   35                 order_region       TEXT        0       None   0
36   36                  order_state       TEXT        0       None   0
37   37                 order_status       TEXT        0       None   0
38   38                order_zipcode       REAL        0       None   0
39   39              product_card_id    INTEGER        0       None   0
40   40          product_category_id    INTEGER        0       None   0
41   41                 product_name       TEXT        0       None   0
42   42                product_price       REAL        0       None   0
43   43               product_status    INTEGER        0       None   0
44   44     shipping_date_dateorders  TIMESTAMP        0       None   0
45   45                shipping_mode       TEXT        0       None   0

In [11]:
# check if datetime format is correct
pd.read_sql("SELECT order_date_dateorders, shipping_date_dateorders FROM supply_chain LIMIT 3;", conn)

  order_date_dateorders shipping_date_dateorders
0   2018-01-31 22:56:00      2018-02-03 22:56:00
1   2018-01-13 12:27:00      2018-01-18 12:27:00
2   2018-01-13 12:06:00      2018-01-17 12:06:00

In [12]:
conn.close()